### ISSUE TITLE
Henson class not found

### ISSUE THREAD

**Issue by zeng1990java** [f2prateek/dart#107]
my build.gradle
compile 'com.f2prateek.dart:dart:2.0.0'
apt 'com.f2prateek.dart:dart-processor:2.0.0'
compile 'com.f2prateek.dart:henson:2.0.0'
apt 'com.f2prateek.dart:henson-processor:2.0.0'
Henson class not found.

**Comment by dlemures** [comment]
Hi @zeng1990java,

Henson is part of Dart, so it works in conjunction with the rest of the library: the DSL is only generated for activities which contain @InjectExtra fields or are annotated with @HensonNavigable.

Thus, if you don't use any of these annotations, the Dart/Henson flow is not complete and the Henson DSL is not generated.

Is this your case?

**Comment by joxad** [comment]
Hi same gradle here, I just created 

`@HensonNavigable
public class RegisterActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }
}
`

But in my other Activity, Henson is not visible.. any idea?

**Comment by dlemures** [comment]
Hi @joxad 
The Henson class is generated at compile time.
Have you rebuild after adding the annotation?

Another possibility: have you added the proguard rules?
https://github.com/f2prateek/dart#proguard

**Comment by joxad** [comment]
@dlemures  : I build and I have nothing. I have disable proguard for the moment.
Do I need to add apt in the gradle as well?

**Comment by dlemures** [comment]
Hi @joxad ,

Yes, if you are using apt, you need to include it in your build script:
https://bitbucket.org/hvisser/android-apt

**Comment by dlemures** [comment]
@joxad @zeng1990java  
any update?

**Comment by joxad** [comment]
Hi, it's strange I have added Henson/Dart in another project and I had no problem. I'll need to recheck the differences between both of them.
In the second one I use apt and it works without problemes, but in the first one, no apt and it seems to do not find Henson at all.

**Comment by stephanenicolas** [comment]
Yes apt is needed so that generated classes (during annotation processes)
get visible to Android studio.

**Comment by dlemures** [comment]
15 days from the last unresolved comment with no updates, closing. 
Can be reopened if required.
