### ISSUE TITLE
Add support for support library fragment

### ISSUE THREAD

**Issue by dlemures** [f2prateek/dart#109]
Currently it is not possible to use Dart to inject extras of a `android.support.v4.app.Fragment`.

**Comment by dlemures** [comment]
https://github.com/f2prateek/dart/pull/6

**Comment by yaming116** [comment]
This will be added in the next version. #111

**Comment by CCorrado** [comment]
*bump* running into this problem now. Realized Dart expects an Android.app.fragment.

**Comment by dlemures** [comment]
The changes to add the shortcut are too big.
We can use:
`Dart.inject(this, getArguments())`
