### ISSUE TITLE
Failed to use Dart/Henson v2 with activity and fragment in different packages

### ISSUE THREAD

**Issue by db-dblank** [f2prateek/dart#112]
I have an activity at com.example.ui.activity.MyActivity and a fragment at com.example.ui.fragment.MyFragment, both with  @InjectExtra.

Maybe related to #70.

```
javax.annotation.processing.FilerException: Illegal name com.example.ui..Henson

Error:(38, 8) error: Unable to write henson navigator for types com.example.ui.activity.MyActivity: Illegal name com.example.ui..Henson

Error:(28, 8) error: Unable to write henson navigator for types com.example.ui.fragment.MyFragment: Illegal name com.example.ui..Henson
```

**Comment by stephanenicolas** [comment]
Thx for the bug report. This should work. As a work around though, pass the
exact package
where to generate Henson as an option to the annotation processor.

This should let you work while we fix the bug.

S.

2016-04-09 15:38 GMT-07:00 db-dblank <notifications@github.com>:

**Comment by rafakob** [comment]
I have exactly the same issue. Bugfix coming?

**Comment by stephanenicolas** [comment]
We didn't have time yet. Don't you wanna submit a PR ? It s open source ;)

S.

Le sam. 28 mai 2016 16:06, Rafał Kobyłko <notifications@github.com> a
écrit :

**Comment by aardouin** [comment]
Any chance my answer here solves the problem ? 
https://github.com/f2prateek/dart/issues/124

**Comment by stephanenicolas** [comment]
@rafakob @db-dblank if you wanna submit a PR to fix the problem, or you don't think the work around is enough, please re-open the issue.

We are open to PR but I don't think we're gonna solve a bug we don't run into. OSS guys, it's yours ;)
