### ISSUE TITLE
Ship proguard rules automatically with henson

### ISSUE THREAD

**Issue by vanniktech** [f2prateek/dart#115]
[SO answer how this can be achieved](http://stackoverflow.com/a/27052696). One thing less to configure plus you as the maintainer have the control of the proguard rules regarding your library, which is less error prone.

There's also something for [Maven](http://stackoverflow.com/questions/14281575/looking-for-a-tutorial-proguard-for-android-maven-project).

**Comment by dlemures** [comment]
Thanks @vanniktech 
Do you want to do a PR?

**Comment by vanniktech** [comment]
Would need to be done [here](https://github.com/f2prateek/dart/blob/master/henson/pom.xml), right?

**Comment by stephanenicolas** [comment]
What would you proguard in Dart 2 ?
Quite some code that needs to be kept by proguard is actually gonna be
generated and depends on the app source code...


2016-06-07 7:31 GMT-07:00 Niklas Baudy <notifications@github.com>:

**Comment by anthonymonori** [comment]
Any progress on this?

**Comment by vanniktech** [comment]
Personally I'm no longer interested in this and hence closing it. Thanks anyways :)
