### ISSUE TITLE
Inject Support Library fragments

### ISSUE THREAD

**Issue by Rhedox** [f2prateek/dart#116]
I can't use Dart with fragments because they inherit from android.support.v4.app.Fragment instead of android.app.Fragment and can't be cast unlike support library activities. It would be neat if Dart could work with support library fragments.

`Error:(100, 13) error: no suitable method found for inject(MainFragment)
method Dart.inject(Object,Object,Finder) is not applicable
(actual and formal argument lists differ in length)
method Dart.inject(Object,Bundle) is not applicable
(actual and formal argument lists differ in length)
method Dart.inject(Object,Activity) is not applicable
(actual and formal argument lists differ in length)
method Dart.inject(Fragment) is not applicable
(actual argument MainFragment cannot be converted to Fragment by method invocation conversion)
method Dart.inject(Activity) is not applicable
(actual argument MainFragment cannot be converted to Activity by method invocation conversion)`

**Comment by dlemures** [comment]
Hi @Rhedox ,

For support fragment you can use:
`Dart.inject(this, getArguments())`

**Comment by NewColours** [comment]
I think this needs to be documenting in the readme
