### ISSUE TITLE
Can't find Henson class 

### ISSUE THREAD

**Issue by HappyImp** [f2prateek/dart#117]
in my gradle 

```
compile 'com.f2prateek.dart:henson:2.0.0'
provided 'com.f2prateek.dart:henson-processor:2.0.0'
```

but can't find Henson in my project.  
I don't know why..

**Comment by soaringEveryday** [comment]
me too

**Comment by soaringEveryday** [comment]
Within your Another Activity, you should remove the @HensonNavigable annotation, then you will see the Henson object

**Comment by HappyImp** [comment]
@soaringEveryday 
Tks ,I will try it again.

if this activity need to get intent and startactivity.what should i do .

@HensonNavigable  can't use with @InjectExtra

才发现也是中国人...  

如果我这个activity 即需要接收前面传过来的intent 也需要去启动别的activity.
这时我这个activity同时用到了@HensonNavigable  注解和@InjectExtra
该怎么办.

**Comment by HappyImp** [comment]
@soaringEveryday 

我在别的activity中没有使用@HensonNavigable ，也无法找到Henson.class
然后我尝试在别的activity上加@HensonNavigable ，然后在主activity中也无法找到

**Comment by dlemures** [comment]
Hi @HappyImp ,

Please have a look at the following issue, you might find the solution there: https://github.com/f2prateek/dart/issues/107

Regarding `@HensonNavigable`, you only need it if you want to navigate to an activity with no `@InjectExtras`. By default, gotoXXX is only generated for activities with `@InjectExtra`.

**Comment by soaringEveryday** [comment]
@HappyImp 
我的理解是Henson找不到这个类是因为编译出错，编译出错的原因就是@HensonNavigable 和@InjectExtra冲突

**Comment by stephanenicolas** [comment]
This issue is closed. Please @soaringEveryday and @HappyImp , GH is generally used in english as its supposed to be more universal than any other language. we would appreciate your next comments to be in english too.
