### ISSUE TITLE
use Dart in MVP

### ISSUE THREAD

**Issue by fansmc** [f2prateek/dart#120]
we use MVP to construct android project, Activity and Fragment be use to V(view) so it can not hold M(model), model be use to handle data .
  P(presenter) hold the interface from V  and Instance from M ,P just use interface to handle UI display , the interface implment by Activity and Fragment.
  when i use Dart in M , it can't find a right inject method .

##ex.

###IView

	public interface IView {
 	   void displayResult(String result);
	}

###Activity

	public class ViewActivity extends AppCompatActivity implements IView {
  	  @Override
 	   public void onCreate(Bundle savedInstanceState, PersistableBundle persistentState) {
  	      super.onCreate(savedInstanceState, persistentState);
    	    setContentView(R.layout.activity_main);
    	    Presenter presenter = new Presenter(this, getIntent().getExtras());
   	     presenter.initMessage();
  	  }

 	   @Override
 	   public void displayResult(String result) {
 	       Log.i("ViewActivity", result);
  	  }
	}
###Presenter

	public class Presenter {
  	  private Model model;
   	 private IView view;

   	 public Presenter(IView view, Bundle bundle) {
  	      this.view = view;
  	      model = new Model(bundle);
  	  }

  	  public void initMessage() {
   	     String message = model.getMessage();
  	      view.displayResult(message);
  	  }
	}

###Model

	public class Model {
	   @InjectExtra("Message")
 	   String message;

 	   public Model(Bundle bundle) {
 	       Dart.inject(this, bundle);
 	   }

  	  public String getMessage() {
    	    return "the message is " + message;
   	 }
	}
if inject in model , it can't use Henson navigable build. how can i do for this ?

**Comment by dlemures** [comment]
Hi @fansmc ,

Add the following annotation to your activity:
```java
@HensonNavigable(model = YourModel.class)
public class ViewActivity extends AppCompatActivity implements IView {
```

**Comment by fansmc** [comment]
thanks very much , it's work !!!  what a amazing lib !!

**Comment by stephanenicolas** [comment]
Thx from all the team ;)

**Comment by dlemures** [comment]
Closing :)
