### ISSUE TITLE
using with setResult

### ISSUE THREAD

**Issue by alexzaitsev** [f2prateek/dart#121]
Hello and thanks for nice library. I've tried to use it and there is one missed thing: using it with `setResult`. Is it possible? Or will this point be added to the enhancements list?

**Comment by stephanenicolas** [comment]
Can you give a more clear example ?

2016-06-13 4:09 GMT-07:00 Alexander Zaitsev <notifications@github.com>:

**Comment by alexzaitsev** [comment]
```
Intent intent = new Intent();
intent.putExtra(EXTRA_GO_DATE, dateGo.getTime());
setResult(RESULT_FIRST_USER, intent);
```

**Comment by stephanenicolas** [comment]
You can still use Henson to create the intent and pass it to setResult, no ?

2016-06-13 5:37 GMT-07:00 Alexander Zaitsev <notifications@github.com>:

**Comment by alexzaitsev** [comment]
I haven't found such example or something helpful.

**Comment by stephanenicolas** [comment]
Henson....build() will return an intent. You simply have to use later on.

Can you give it a try and close the issue if it's solved ?

2016-06-13 5:42 GMT-07:00 Alexander Zaitsev <notifications@github.com>:
