### ISSUE TITLE
Unable to write henson navigator + cannot find symbol class Henson

### ISSUE THREAD

**Issue by hamid-rocket** [f2prateek/dart#125]
I put @InjectExtra on two different activities, and now I'm getting two errors:

1. error: Unable to write henson navigator for types ...MyFirstActivity: Illegal name com.rocketinternet.spaceport.ui..Henson -> Here the two dots before Henson are weird! This happens for both of my activities.

2. error: cannot find symbol class Henson. -> because Henson cannot generate the Henson navigators on the first step I get this error as well.

By the way it works if I put @InjectExtra only on one activity, but when I add the annotation to more activities this bug happens.

**Comment by aardouin** [comment]
Here is the solution : 
https://github.com/f2prateek/dart/issues/124

**Comment by stephanenicolas** [comment]
@hamid-rocket , yes the issue #124 should solve your problem. The bug you mention was also reported previously in #112
