### ISSUE TITLE
Method count footprint shown in README

### ISSUE THREAD

**Issue by anthonymonori** [f2prateek/dart#134]
Would be nice to mention the method count that is being added when I start using Dart and Henson just as a reference. It is nice to know what am I (or more like how many am I) pulling in when deciding to use these libraries. You can get an idea by using the latest Android Studio to measure your project's footprint with a tool called [APK analyzer](http://android-developers.blogspot.dk/2016/09/android-studio-2-2.html) baked into the IDE

**Comment by f2prateek** [comment]
We can't give an accurate measurement. This is a code generation library. The exact weight of the generated code will depend on how you use it.

You can use the method count website for the runtime components.
