### ISSUE TITLE
Add topics

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#152]
To @f2prateek , can you add some topics to dart main page ?
![image](https://cloud.githubusercontent.com/assets/1832925/24945809/1182216e-1f61-11e7-902f-f40655fdcee7.png)

Like in TP:
![image](https://cloud.githubusercontent.com/assets/1832925/24945814/1c9a329e-1f61-11e7-9abd-c273f081eb77.png)

**Comment by f2prateek** [comment]
@stephanenicolas which topics would you like to add?

**Comment by stephanenicolas** [comment]
Not sure about what is suggested or if it's possible to add new ones. In bulk, android intent intent-builder navigation ?

**Comment by f2prateek** [comment]
Ah neat, didn't realize it had suggestions. They were mostly off though https://cloudup.com/cJ5hcb_kZ_4.

Add what you suggested + some recommended ones https://cloudup.com/cZQq9f--qDY

**Comment by stephanenicolas** [comment]
Thx @f2prateek
