### ISSUE TITLE
Need proper documentation

### ISSUE THREAD

**Issue by TakeoffAndroid** [f2prateek/dart#155]
I am completely stuck up regarding the usage of dart and henson. I have copy-pasted following snippet in my code to navigate to another scren, but now am directionless to fixe the issue

  Intent intent = Henson.with(this)
                        .gotoOneMoreActivityActivity()
                        .extra(new ParcelExample())
                        .build();

Error:

Error:(102, 33) error: cannot find symbol variable Henson

From where i have to import Henson class??

**Comment by stephanenicolas** [comment]
Did you follow the setup in the readme ? Did you setup the annotation
processor ?

2017-04-25 21:08 GMT+02:00 Takeoff Android <notifications@github.com>:

**Comment by TakeoffAndroid** [comment]
Yep I did. I followed all the steps :-(

**Comment by chandruf22** [comment]
I am trying to star an activity from fragment using Henson.with(getActivity).gotoMyProfileActivity.build(). But its not working. Also I am not getting the usage of @HensonNavigable annotation and packaging concept setup in build.gradle like 'henson.package' something which was mentioned in the readme. Please clarify my queries. Really it is an amazing library, but documentation part is lagging since samples of github project is also not a studio project i guess.

**Comment by stephanenicolas** [comment]
Yes, the sample project works with Android studio.

Can you show:
* the code of the target activity (class and annotated fields if there are)
* you gradle setup


2017-04-26 4:14 GMT+02:00 chandruf22 <notifications@github.com>:

**Comment by TakeoffAndroid** [comment]
Kudos. It worked after Build - Rebuild Project.  Gradle build was the culprit. Before closing this issue, I hope this library will not startActivityResult(REQUEST_CODE) behaviour?.

**Comment by TakeoffAndroid** [comment]
I am planning to popularise this library by creating a blog in my https://takeoffandroid.com. Hope this will reach good number of target users soon. Thanks for creating such a library to reduce boiler plate codes for intent value creation.

**Comment by stephanenicolas** [comment]
Thanks for trying it and helping to make it more popular.

Btw, @HensonNavigable is used when you want to navigate to an activity that
has no @InjectExtra fields. It can then be discovered by Henson and it will
allow to navigate to it via the Henson class.



2017-04-26 8:00 GMT+02:00 Takeoff Android <notifications@github.com>:
