### ISSUE TITLE
Dart's @Optional annotation collides with butterknife.Optional

### ISSUE THREAD

**Issue by nono240** [f2prateek/dart#18]
There're big chances that ButterKnife is used along Dart, and I spent 45 minutes to debug that "Optional" thing. I was using the Butterknife's annotation on my injected fields...

Because the name collides, I had to prefix those annotations with the package name, and my fields really looks ugly now.

**Comment by intrications** [comment]
@stephanenicolas @f2prateek 

Looks like butterknife may be ditching @Optional anyway:
https://github.com/JakeWharton/butterknife/issues/239

@Nullable looks like a good replacement for this library as well.

**Comment by stephanenicolas** [comment]
Thanks for this update, @f2prateek, I would be happy to implement that if
you want. We can even keep both annotations for 1.2.x if you want.



2015-03-10 6:10 GMT-07:00 Michael Basil <notifications@github.com>:

**Comment by f2prateek** [comment]
Yeah I talked with Jake about it. For now, I'm going to respect ANY `@Optional` annotation, and add support for `@Nullable` in the future too.

**Comment by stephanenicolas** [comment]
Cool ! Do you need some code to do that ?

We have some in the RoboGuice's NullableUtil class if my memory is good.

2015-03-10 12:04 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Comment by f2prateek** [comment]
Thanks, I'll take a look at it. I won't get to it until the weekend most likely though, PR's appreciated if you'd like it in sooner :)

**Comment by f2prateek** [comment]
Closing in favor of #28 and #27
