### ISSUE TITLE
Add us as admins

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#187]
Hi @f2prateek , can you add @dlemures and me as admins please ?
We are considering adding a 3rd groupon coworkers, the author of https://github.com/f2prateek/dart/pull/180/files
(Pratyush)

**Comment by f2prateek** [comment]
I added him as a collaborator https://cloudup.com/cMi-vd6k73H. However, I don't see an option to add as Admin, let me know if if there's some specific way I can do that.
