### ISSUE TITLE
Automatically generate extra key

### ISSUE THREAD

**Issue by Christophe668** [f2prateek/dart#19]
If I may suggest a new feature, it would be great to have the ability to inject extras without giving an 'extra key' the same way FragmentArgs works : 
https://github.com/sockeqwe/fragmentargs

It generates default keys if none is given.
It would avoid boilerplate code when creating an intent such as     *intent.putExtra(SampleActivity.EXTRA_INT, anInt);*
The intent could then be created like proposed in the issue : 
https://github.com/f2prateek/dart/issues/13

What do you think?

**Comment by f2prateek** [comment]
Implemented in #23, the variable name is automatically used as an extra key if one is not provided.

**Comment by Christophe668** [comment]
Great thx !
