### ISSUE TITLE
Change library motto

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#194]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1832925/34633348-e99b2b98-f27b-11e7-890d-da6e3c2caa19.png">

Can you change `injections` for `binding` ? @f2prateek , I can't do it. Or even:
`Extras binding and intent builders for Android apps.`

**Comment by f2prateek** [comment]
done! https://cloudup.com/cV7R1C5hDJK
