### ISSUE TITLE
Wrong annotation scope

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#20]
InjectExtra should have CLASS Retention, not runtime.

**Comment by f2prateek** [comment]
Thanks!

**Comment by stephanenicolas** [comment]
Hi @f2prateek , I have been hacking Dart a bit to add support for butterknife's optional annotation as well as yours. Are you interested in this feature ? (There is an issue pending : #18 ) and could you release quickly a version with the patch ?

**Comment by f2prateek** [comment]
@stephanenicolas I was planning on releasing 1.2.0 right now. I can wait for your patch, or merge it in for 1.2.1. I'm fine with either.
