### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [f2prateek/dart#212]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by f2prateek** [comment]
I will let @dlemures and @stephanenicolas give the final green light for this - but from my side I would be ok with adding an icon!

**Comment by jbeguna04** [comment]
Thank you for your response

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/40259877-8c66507a-5b2a-11e8-93f6-b97e0600821a.png)
Greetings to all, This is my proposal of the designs on the logo, Feel free to have suggestions of the idea.
Thank you in advance!

**Comment by dlemures** [comment]
I really like the icon!!  From my side ✅
@stephanenicolas

**Comment by jbeguna04** [comment]
Thank you sir

**Comment by jbeguna04** [comment]
If i may add, the files for the design is ready for use. If you wanted to use those i can upload it here
Thank you for all of your comments

**Comment by stephanenicolas** [comment]
Thx for the icon @jbegona04. Everyone looks happy with it

**Comment by jbeguna04** [comment]
Im just waiting for your go signal to upload the files here sir, Please allow me to make a pull request of the designs

**Comment by jbeguna04** [comment]
![dart](https://user-images.githubusercontent.com/35353768/40265290-29049ec2-5b68-11e8-9c26-2b6384f422f0.png)
Other color combinations

**Comment by dlemures** [comment]
Actually I prefer this new combination. 
Plz feel free to make a PR or upload/publish the images .

**Comment by f2prateek** [comment]
Me too! I really like blue/red/purple one in  https://github.com/f2prateek/dart/issues/212#issuecomment-390380681 (second row, in the middle).

**Comment by jbeguna04** [comment]
thank you for all of your responses, I promise to make a PR for a moment.
