### ISSUE TITLE
Why is MyActivity1NavigationModel extends Activity?

### ISSUE THREAD

**Issue by cooperkong** [f2prateek/dart#216]
Hi, there
Just reading through the migration guide and found below.

`class MyActivity1NavigationModel extends Activity{
  @InjectExtra String foo;
}`

**Comment by stephanenicolas** [comment]
It's a mistake, can you tell use where you found it ?
NavigationModel are simple pojos, if there is a hierarchical dependency
between 2 activities, then the models also have to extend from each other.
But NavigationModel don't extend from Activities.

2018-05-30 21:23 GMT-07:00 WenChao Kong <notifications@github.com>:

**Comment by cooperkong** [comment]
I have edit the page [https://github.com/f2prateek/dart/wiki/DH3-Migration-guide](url) in Step1
