### ISSUE TITLE
[DH]Not generated  “IntentBuilder”

### ISSUE THREAD

**Issue by LinZhang6530** [f2prateek/dart#227]
![image](https://user-images.githubusercontent.com/12758609/45629649-7477c800-bac9-11e8-91c9-ef3184e07c97.png)

**Comment by stephanenicolas** [comment]
We need to see your setup.
Here are a few things:
In the navigation module, make sure to:
* Enable annotation processor for Henson
* Use annotations on your navigation model classes.

**Comment by LinZhang6530** [comment]
Thank you, the problem has been solved
