### ISSUE TITLE
Can't use DH3 in Android Dynamic Feature Module

### ISSUE THREAD

**Issue by yeuristic** [f2prateek/dart#240]
I've module that apply plugin: 'com.android.dynamic-feature'
when I try to add apply plugin: 'dart.henson-plugin'
I got this error message:

`A problem occurred evaluating project ':xxxxx'.
> Failed to apply plugin [id 'dart.henson-plugin']
   > 'android' or 'android-library' plugin required.`

Please help, thanks

**Comment by stephanenicolas** [comment]
Hi, do you want to create a PR and test wether it worka for you ?
We don't have a dynamic feature to test this on.

**Comment by yeuristic** [comment]
Hi, this is my PR https://github.com/f2prateek/dart/pull/241/files

**Comment by stephanenicolas** [comment]
Hi Yusuf, that's great ! Could you test the PR is working for you ? Again,
we can't test this on our side..

**Comment by yeuristic** [comment]
Hi Stephanenicolas,
I've already tested it in My Project before submitting the PR. And it works well in My Project.
Thank you

**Comment by stephanenicolas** [comment]
I close the issue, it's been fixed in 3.1.3 which I just released. It will be available in 3 hours on maven central. Thx @yeuristic, good job !

**Comment by stephanenicolas** [comment]
I close the issue, it's been fixed in 3.1.3 whichis available on maven central. Thx @yeuristic, good job !
