### ISSUE TITLE
Explain how default values work in README.md

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#29]
Suppose we have an `@Optional @InjectExtra boolean foo`. Can we use `foo = false/true` to initialize a default value in case the field is not found ?

This is missing in the documentation.

**Comment by f2prateek** [comment]
Yup, you would do `@InjectExtra String foo = "defaultFoo";` to use a default value before 'injection'. You can also add `@Optional` if the value may not be provided when you call the `inject` method.
