### ISSUE TITLE
Do not throw UnableToInjectException if there's no @InjectExtras annotation found

### ISSUE THREAD

**Issue by renaudcerrato** [f2prateek/dart#38]
I'm using Dart in my `BaseFragment` implementation, but some of my fragments use arguments without injections. Doing so, I'm getting an `UnableToInjectException` because there's no annotations defined...

The correct behavior should be to silently return.

**Comment by f2prateek** [comment]
Yup, can you post the exact error?

**Comment by renaudcerrato** [comment]
Mmmmm.... Forget about it: cleaning the project solved it...
