### ISSUE TITLE
Use android.support.annotation.Nullable instead of com.f2prateek.dart.Optional

### ISSUE THREAD

**Issue by rockerhieu** [f2prateek/dart#41]
I think it will make more sense if Dart use `android.support.annotation.Nullable` instead of `com.f2prateek.dart.Optional`

**Comment by f2prateek** [comment]
Dart already does this https://github.com/f2prateek/dart/blob/master/dart/src/main/java/com/f2prateek/dart/Optional.java#L31

**Comment by rockerhieu** [comment]
Weird, I used `Nullable` and it didn't work, that's why I filed this issue. Let me double check.

**Comment by rockerhieu** [comment]
Does it include in the latest release of `Dart`?

**Comment by f2prateek** [comment]
It's not released yet.

**Comment by rockerhieu** [comment]
Gotcha.
