### ISSUE TITLE
[Dart 2.0] Henson doesn't take into account inherited @InjectExtra annotated fields to generate the DSL.

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#53]
To be fixed before RC 2 : 
```java
class A extends Activity {
  @InjectExtra String s;
}
class B extends A {
  @InjectExtra String t;
}
```
Henson's generated DSL should include the inherited `s` field;

Note : if B doesn't define any @InjectExtra annotated field, the DSL is not even generated for it...

@f2prateek do you already have a mechanism to collect inherited fields in a given class ?

**Comment by f2prateek** [comment]
We do this for Dart here (not reusable though)- https://github.com/f2prateek/dart/blob/b90a7af641e8c996c82922b40f02d08eca226d72/dart-common/src/main/java/com/f2prateek/dart/common/AbstractDartProcessor.java#L119

https://github.com/f2prateek/dart/blob/08001ad8f8b89cde656228be4f2f3cbf2bbf478a/dart-processor/src/main/java/com/f2prateek/dart/processor/ExtraInjectionGenerator.java#L75

Basically just walk the class hierarchy, and keep your own list of fields that are annotated, and use it to generate the code.

**Comment by stephanenicolas** [comment]
Cool, I will look into the issue after fully integrating RC 1.

Did you see my other PR ?
#52 ?



2015-07-22 13:48 GMT-07:00 Prateek Srivastava <notifications@github.com>:
