### ISSUE TITLE
[DART 2.0] Allow to extend the intent builder to a subclass

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#56]
@Macarse @johncarl81 @f2prateek, please check :

### Proposal of extension to Henson DSL.

The problem is the following. Let's say we have 
```java
class A {
 @InjectExtra String s;
}

@Henson class B {
}
```

It would be possible, only in the case of a subclass, to use the DSL of class `A` to build an intent for class `B`. Some conditions apply, they are discussed later on.

It would allow to do something like (pseudo code): 
```java
if (condition) {
  gotoA();
} else {
  gotoB();
}
```

For now, the only way to perform such constructs is to build fully independent intents to go to both `A` and `B`.

The proposed enhanced DSL syntax would be 
```java
Henson.with(context)
 .gotoA()
 .extendTo(B.class)
 .build();
```

The generated code would then build a normal intent to goto `A` but would ultimately invoke `setClass(context, B.class)` on the intent being built when the verb `extendTo` is invoked.

### Conditions and verification

It is important to emphasize that such use case can actually follow a normal good-practice of OO inheritance. *However*, in order to promote good practices and avoid intent mess, we should not allow to extend the DSL to classes that don't have an inheritance link. That would be a very bad design to share same intent keys for unrelated classes and the would destroy constraint enforcement checking philosophy of Henson.

* it is possible to check at *compile-time* that `B` extends `A`. 
* in the same way, we should also check that `B` contains no non-optional `@InjectExtra` annotated fields (as this would imply an intent to `A` would only build an incomplete intent to B). Optional fields are allowed though. This can also be checked at *compile-time*.

Nevertheless, the call to `extendTo` will be executed at *runtime* only. We won't be able to perform the checks before runtime and it will require reflection (which breaks the Dart philosophy). 
--> See proposal enhancement for *compile-time* check.

### Proposal enhancement to get compile time verification
We could slightly adapt the former proposal to perform a compile-time constraint verification :

```java
Henson.with(context)
 .gotoA()
 .extendToB()
 .build();
```

In that case, the generated code would allow to switch to B if and only if all conditions described above have been met. Otherwise the DSL extension will not be generated.

### Additional feature of the enhanced proposal 

It is probably possible to return the internal state `B.AllSet` after `extendToB()`. There are maybe some additional constraints but it looks feasible. In that case, after the call to `extendToB()` it would even be possible use the `B$$IntentBuilder` DSL to set optional extras of `B` : 

```java
Henson.with(context)
 .gotoA()
 .extendToB()
 .optionalFooInB("foo");
 .build();
```

In that case the initial condition would be solved by the very elegant : 
```java
A.AllSet state = Henson.with(context)
 .gotoA();

if (condition) {
 state.extendToB()
 .optionalFooInB("foo");
 .build()
}
```
### Conflict

This proposal conflicts with #54. 

Or maybe the best would be to allow abstract classes to generate a DSL if and only if they are extended (which would change the final state of the DSL state machine). Indeed an abstract class DSL would not provide the build method, only subclasses would, in case we can implement the enhanced proposal.

### Schedule

Dart 2.0 RC 3

**Comment by stephanenicolas** [comment]
WDYT @f2prateek . @Macarse thinks it adds too much complexity to the lib.

**Comment by johncarl81** [comment]
@stephanenicolas I've read this a couple times, and I'm a little lost, possibly I'm out of the conversation as Henson is new to me.  Could you give a concrete examples?  Is 'A' an Activity?

**Comment by stephanenicolas** [comment]
They are all activities. Let's say you have 2 subclasses of an abstract
class. Depending on a condition you will want to go to 1 of the 2 concrete
subclasses. The question is : how to build an intent an minimize code as
they share extras.


2015-07-29 8:34 GMT-07:00 John Ericksen <notifications@github.com>:

**Comment by stephanenicolas** [comment]
This seems over complicated. We drop it for now.
