### ISSUE TITLE
[Dart 2.0] Henson can't be used to create an intent for a class that doesn't declare an extra as it is used only by its fragments

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#58]
The DSL doens't about the extra when parsing the intent, and there is no way to solve this at compile-time.

For now a workaround is to also declare the InjectExtra in the activity. But it looks fragile and the field could be removed during maintenance (needs a good comment). 

Maybe we could introduce an annotation like `@ForFragmentsOnly @InjectExtra String s` ?

**Comment by f2prateek** [comment]
not sure I quite understand the issue here. Could you clarify with an example?

**Comment by stephanenicolas** [comment]
If a fragment declares an InjectExtra annotation field, there is no way
that Henson can detected it when building the DSL of the activity(ies) that
will contain the fragment.

The the DSL doens't allow to fill the value of the field.

2015-07-24 16:44 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Comment by f2prateek** [comment]
That makes more sense, but what does the `@ForFragmentsOnly` annotation do?

**Comment by stephanenicolas** [comment]
Just tell maintainers : I don't use this extra entry directly, but my
fragments do, don't erase me.
But then the DSL will allow to fill the extra for the fragments.

I actually think it would enforce a more complicated way of doing things
than Android allows to, but that would be better structured and reduce
intent mess.


2015-07-24 16:48 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Comment by stephanenicolas** [comment]
WDYT of this for RC 2 ? @f2prateek

**Comment by stephanenicolas** [comment]
In the case of fragments or pojos (i.e. non activities) using @InjectExtra, they should not have their own intent builders and should not appear in the goto list of Henson.

**Comment by stephanenicolas** [comment]
We can combine this with #84 and #67 .

For instance, let's take an Activity A that uses a class M as model and contains 2 fragments F0 F1.
We could use : 
```
@HensonNavigable( model = M.class, fragments = F0.class, F1.class } )
class A {
}
```

Then Henson would allow : 
```
  Henson.with( context )
               .gotoA()
               .<dslProvidedByM>
               .fragmentF0()
               .<dslProvidedByF0>
```

There are still a couple of issues to address : 
* redundancy between the @InjectExtras of Fragments and activity / model
* Fragments using a model too
* using multiple fragments to build an Intent of A.

**Comment by dlemures** [comment]
+1

**Comment by vjames19** [comment]
I would like to see this added to Henson.

**Comment by stephanenicolas** [comment]
I would propose : 

```java
Henson.with( context )
               .gotoA()
               .<dslProvidedByA>
               .forFragmentF0()
               .<dslProvidedByF0>
               .endFragmentF0
```

Those would be treated as optional when defining the activity intent.
They would appear in a state after all required extras for A are set.
closing them would go back to this state in the state machine.

**Comment by stephanenicolas** [comment]
This is also too complicated and is on the way to release of DART 2.

Moreover, Henson already helps and a simple (and clean actually) workaround is 
![image](https://cloud.githubusercontent.com/assets/1832925/13237749/21605508-d983-11e5-9865-d68bb6d563e9.png)

We add a sample.

**Comment by talenguyen** [comment]
Henson support Intent builder. But, for Fragment we need Bundle instead. So, I think it need to improve for Fragment. I tested in version 2.0.2 and saw that builder for Fragment look so weird. 

```java
public CategoryListFragment$$IntentBuilder(Context context) {
    intent = new Intent(context, CategoryListFragment.class); // Intent for fragment?
  }

  public CategoryListFragment$$IntentBuilder.AllSet parentId(String parentId) {
    bundler.put("parentId", parentId);
    return new CategoryListFragment$$IntentBuilder.AllSet();
  }

  public class AllSet {
    public Intent build() {
      intent.putExtras(bundler.get());
      return intent;
    }
  }
```
