### ISSUE TITLE
[Dart 2.0] Do not release dart sample

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#66]
It is currently shipped to sonatype for every release. I remember there is a simple release.skip to insert in the pom to prevent that from happening..

**Comment by f2prateek** [comment]
Is there any disadvantage of uploading it? It's convenient to be able to go back and install an old build of the sample app.

**Comment by stephanenicolas** [comment]
I never used that and usually only release word wide libs artifacts but if
you need this, close the issue.

2015-07-27 17:53 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Comment by f2prateek** [comment]
Cool, yeah I wouldn't be against skipping the samples and doesn't make a big difference either way. If you can make it work, go for it!
