### ISSUE TITLE
[DART 2] Henson support for List and SparseArray containing objects annotated with @Parcel

### ISSUE THREAD

**Issue by trungie** [f2prateek/dart#72]
When passing a `List` or `SparseArray` the generated $$IntentBuilder does not recognise the typed class as `@Parcel` but only has support for classes marked with `Parcelable` which works against of the strength of the Parcel-Dart2-Henson combination.

**Comment by iainconnor** [comment]
Believe I got a fix for this at https://github.com/f2prateek/dart/pull/76 if you're interested

**Comment by stephanenicolas** [comment]
We have enhanced Dart 2. Everyhting is fully supported now. We will document as some types require Parceler to work.
