### ISSUE TITLE
Remove javapoet from non-processor modules

### ISSUE THREAD

**Issue by aurae** [f2prateek/dart#74]
The `compile` dependency graph for *dart* looks like this:

```
build.gradle:

compile "com.f2prateek.dart:dart:2.0.0-RC1"
apt "com.f2prateek.dart:dart-processor:2.0.0-RC1"
```

```
./gradlew :app:dependencies:

{...}

+--- com.f2prateek.dart:dart:2.0.0-RC1
|    +--- com.f2prateek.dart:dart-annotations:2.0.0-RC1
|    |    \--- com.squareup:javapoet:1.0.0
|    \--- com.squareup:javapoet:1.0.0
```

Both the `dart-annotations` and `dart-common` modules include a dependency on `com.squareup:javapoet`, which isn't needed (as far as I can tell from scanning the source code). Please consider leaving this dependency in only for the processor portion of the library.

**EDIT**: As a quick fix, one can exclude javapoet explicitly for the compile artifact:
```
compile ("com.f2prateek.dart:dart:2.0.0-RC1") {
    exclude group: "com.squareup", module: "javapoet"
}
apt "com.f2prateek.dart:dart-processor:2.0.0-RC1"
```

**Comment by f2prateek** [comment]
Makes sense, wanna submit a PR?

**Comment by aurae** [comment]
Will do!

**Comment by mopsalarm** [comment]
could you please merge this?

**Comment by f2prateek** [comment]
I haven't seen a PR yet.

**Comment by mopsalarm** [comment]
https://github.com/f2prateek/dart/pull/75

**Comment by f2prateek** [comment]
Thanks!
