### ISSUE TITLE
Henson should ignore absract classes with @InjectExtra annotation

### ISSUE THREAD

**Issue by seato** [f2prateek/dart#79]
As I try to integrate Henson into my app I get a lengthy list of errors that follow this format: `error: Unable to write henson navigator for types SomeAbstractClass: Illegal name .Henson`.

I notice there's a unit test in place which says that Henson should ignore abstract classes in com.f2prateek.dart.henson.processor.HensonNavigatorGeneratorTest#henson_doesntGotoAbstractClasses

but it doesn't seem to be the case if there's an @InjectExtra annotation. Is there a way to work around this?

**Comment by stephanenicolas** [comment]
we will investigate that. Thx @seato 

Also, we want to add a mechanism so that Henson class generation is more robust. There is already an issue open for that. The idea is that a single Henson call should fail when there is an error, not all Henson call should be marked as errors as it makes it much harder to find the issue.

**Comment by stephanenicolas** [comment]
@f2prateek I work with @seato at Groupon. Richard has been assigned to move on and refactor our app using Dart 2 (we had no resource to complete the refactor, which is quite big for us..). 

Do you mind if I had him as a contributor. Richard knows how to make PRs, wait for reviews and merge. ;)

**Comment by f2prateek** [comment]
@stephanienicolas Not at all,  feel free to add him as a contributor.  I think you should be able to, but let me know if not and I can add him.

**Comment by stephanenicolas** [comment]
@seato we need a more detailled bug report..

**Comment by seato** [comment]
@stephanenicolas I'm not able to reproduce this crash anymore, I'll go ahead and close this issue.
