### ISSUE TITLE
Android studio recent changes doesn't require separate artifacts anymotr

### ISSUE THREAD

**Issue by stephanenicolas** [f2prateek/dart#81]
Hi @f2prateek,

I am back to dart 2. Hioefully thus time i can finish pour migration..and we can release dart 2 + Henson.

There were some recent changes in AS. We don't need the apt plugin and scope anymore. If an artifact contains both the annotation processor and runtime code, Android Studio will work fine. The annotation processor can be proguarded and the generated code can be called from AS. 

Thus I would change dart 2 to get artifacts with both runtime and annotation processor bundled together. One for Henson, one for dart. Maybe one parent also. 

Is it fine for you ?

**Comment by f2prateek** [comment]
SGTM!

**Comment by stephanenicolas** [comment]
Nope. After talking with Hugo Visser from android-apt plugin (https://bitbucket.org/hvisser/android-apt), I realized that I didn't understand his statement : the plugin is still the best option. Having one artifact is messy, and not every one uses proguard to prevent the annotation processor from entering the apk, and not even everyone uses gradle... 

I close the issue, we should keep separate annotation processing & runtime artifacts.
