### ISSUE TITLE
Being added as a contributor

### ISSUE THREAD

**Issue by dlemures** [f2prateek/dart#83]
Hi guys,

First of all congratulations for the library, it is amazing!

I'd like to be added as a contributor to help you continue with this. Currently I'm working with Stephane on it.

Thanks!

**Comment by stephanenicolas** [comment]
+1. Are you ok @f2prateek ?

**Comment by Macarse** [comment]
Why do you guys need to be contributors? Can't you just send PRs.

On Thu, Jan 28, 2016 at 12:07 PM, Stéphane Nicolas <notifications@github.com

**Comment by stephanenicolas** [comment]
It's about Daniel taking an active part in Dart / Henson's development.

**Comment by dlemures** [comment]
Yeah :v:

**Comment by f2prateek** [comment]
Works for me! I do agree with @Macarse that being a contributor isn't necessary to be take an active part in the development process, but @stephanenicolas has been the main steward of the project and I don't want to get in the way :)

I've added @dlemures as a contributor.

**Comment by f2prateek** [comment]
Hey @dlemures @stephanenicolas @Macarse - just wanted to get an idea of what's required for shipping a stable release of v2. There are a few open issues and changes on master that haven't been deployed yet. Just so I can let people know who ask me what the status is!
