### ISSUE TITLE
[DART 2] Henson not able to detect extras from external target class

### ISSUE THREAD

**Issue by dlemures** [f2prateek/dart#84]
When an activity defines its extras in an external class and injects them through `Dart.inject(Object target, Activity source)`, Henson cannot find them.

A possible solution may be a new annotation. It could be used to do two things:
1. Set target class.
2. Let Henson know where to look for more extras.

For instance: `@InjectExtraTarget private Model model = new Model();`...

**Comment by stephanenicolas** [comment]
This has been solved by issue #67
