### ISSUE TITLE
@InjectExtra not working with startActivityForResult

### ISSUE THREAD

**Issue by Shargotth** [f2prateek/dart#87]
Hi,

My "@InjectExtra" annotations doesn't work when I start my activity by launching "startActivityForResult". Is that a normal beavior?

Thanks,

**Comment by dlemures** [comment]
Hi @Shargotth 

I should work using startActivityForResult. 
Could you provide more details or some code? (target activity @InjectExtra definition code, intent creation code, ...)

Thanks

**Comment by stephanenicolas** [comment]
This doesn't make much sense, it should work without any problem. Please re-open if needed and add detals.
